arki55/features/T9-github-build-checks-fuse feat: Added step to check that verifies if configure command has really configured the needed UI type

diff --git a/.github/workflows/build_linux_gtk3.yml b/.github/workflows/build_linux_gtk3.yml
--- a/.github/workflows/build_linux_gtk3.yml
+++ b/.github/workflows/build_linux_gtk3.yml
@@ -23,18 +23,27 @@ jobs:
       - name: (4) Configure for linux
         run: |
           echo "Running configure .."
-          ./configure --with-gtk
+          ./configure --with-gtk | tee ./configure.out
 
-      - name: (5) Make
+      - name: (5) Verify output from configure
+        run: |
+          lines1=(`cat "./configure.out" | grep -c "User interface: gtk"`)
+          lines2=(`cat "./configure.out" | grep -c "Using GTK 3: yes"`)
+          if [[ "$lines1" -ne "1" || "$lines2" -ne "1" ]]; then
+            echo "Error: User interface not configured for type GTK3!"
+            exit 1
+          fi
+
+      - name: (6) Make
         run: |
           echo "Running make .."
           make
 
-      - name: (6) Install (+sudo)
+      - name: (7) Install (+sudo)
         run: |
           echo "Running make install .."
           sudo make install
 
-      - name: (7) Finish
+      - name: (8) Finish
         run: |
           echo "🍏 Finishing with status ${{ job.status }}."
diff --git a/.github/workflows/build_linux_null.yml b/.github/workflows/build_linux_null.yml
--- a/.github/workflows/build_linux_null.yml
+++ b/.github/workflows/build_linux_null.yml
@@ -22,18 +22,26 @@ jobs:
       - name: (4) Configure for linux
         run: |
           echo "Running configure .."
-          ./configure --with-null-ui
+          ./configure --with-null-ui | tee ./configure.out
 
-      - name: (5) Make
+      - name: (5) Verify output from configure
+        run: |
+          lines=(`cat "./configure.out" | grep -c "User interface: null"`)
+          if [[ "$lines" -ne "1" ]]; then
+            echo "Error: User interface not configured for type null UI!"
+            exit 1
+          fi
+
+      - name: (6) Make
         run: |
           echo "Running make .."
           make
 
-      - name: (6) Install (+sudo)
+      - name: (7) Install (+sudo)
         run: |
           echo "Running make install .."
           sudo make install
 
-      - name: (7) Finish
+      - name: (8) Finish
         run: |
           echo "🍏 Finishing with status ${{ job.status }}."
